### ISSUE TITLE
Kvatch Rebuilt - sort order versus OOO/FCOM and (Open) Better Cities

### ISSUE THREAD

**Issue by charabaruk** [loot/oblivion#1633]
Per readme of Kvatch Rebuilt 3.0:

> It is advisable to load Kvatch Rebuilt after OOO/FCOM and (Open-) Better Cities.

What would be the best way to go about this? It doesn't seem like `after` supports regex for the name property of items, but there are a lot of individual files that would need to be listed just for Better Cities.

**Comment by charabaruk** [comment]
I think I'm going to put Kvatch Rebuilt into the cities group and then just put in all the regular plugins for it into the `after` list.

**Comment by sibir-ine** [comment]
Does Kvatch Rebuilt even conflict with Better Cities, Open Cities, OOO, or FCOM, specifically through records or BSA-packed assets? I'm not super familiar with any them & can't check in xEdit at the moment (I can check later), but it doesn't sound like it actually would. If they indeed do, load afters would still probably be better (unless there are other good reasons to load KR so late). You'd have to add load afters for some of the BC & OC plugins anyway to avoid cycles.

**Comment by charabaruk** [comment]
I'm not too sure, but KR definitely touches quite a few things outside of Kvatch itself, due to the quest line, and it wouldn't be at all surprising if there are potential conflicts. Since KR is a city replacer (in a way) it should be in the cities group, so then ordering versus OOO and FCOM isn't an issue anyway since those are in an earlier group.

**Comment by charabaruk** [comment]
I took the approach I mentioned earlier in #1641

**Comment by sibir-ine** [comment]
The **Cities** group predates me, but it only contains Better Cities & Open Cities plugins, so I think it's more for them specifically than city overhauls in general (despite it's description). I'm therefore reluctant to add new plugins to that group without extensive testing. I assume the group is mostly due to the extent of the edits BC & OC make resulting in conflicting mods consistently producing worse results when loaded after & requiring patches instead (Open Cities completely relocates the cities into the main worldspace & therefore renders edits by other mods inaccessible, Better Cities extensively edits each city & offers its own open cities options). I don't think Kvatch Rebuilt is in the same boat; I imagine most other conflicting Kvatch mods would simply be incompatible. I've also looked at them in xEdit, & KR only conflicts with BC & OC in the landscape & path grid records of a single cell in Anvil. Load order shouldn't matter with OC due to the fact that it relocates the Anvil worldspace anyway, so I don't think you'd even be able to access KR's edits there without a patch (there is one for OCR). Not sure about BC, but I'd like to get the opinion of its current maintainer before changing the load order of these mods. It's the same in LOOT as it is in BOSS (& has been for many years), so it'd be good to get an opinion from both authors first. Judging by their compatibility notes for each other's mods, I don't think they've checked very recently (KR is referencing Open BC which is no longer offered through separate plugins, [BC](https://en.uesp.net/wiki/Better_Cities:Compatibility_With_Other_Mods) links to an [ancient deleted page](https://www.nexusmods.com/oblivion/mods/887), presumably for KR, that doesn't even appear to be archived).

As for OOO, it's just a couple of conflicts in records that are easily resolved with either a Bashed Patch or manually through xEdit. They conflict either way you load them, so a load rule wouldn't be a good solution for this. I'd rather let users decide which should take priority if they're really unwilling to resolve those conflicts. They could overwrite LOOT's default sorting with a user-added load after.
