### ISSUE TITLE
C.Water for unofficial patches?

### ISSUE THREAD

**Issue by Infernio** [loot/oblivion#207]
Opening this as an issue instead of a pull request because I'm not sure if there's a reason these haven't been added (e.g. breaking a lot of third party water mods).

Here's an example for a conflict with the Unofficial Shivering Isles Patch which is not resolved due to a missing C.Water tag:

![loot-cwater1](https://user-images.githubusercontent.com/2845240/87831238-30031200-c883-11ea-9ad5-be2be73cea76.png)

And here's one with the Unofficial Oblivion Patch:

![loot-cwater2](https://user-images.githubusercontent.com/2845240/87831260-5163fe00-c883-11ea-9b7e-c0eeeb37439d.png)

**Comment by MacSplody** [comment]
I'm don't know the reason for it, but `C.Water` is listed as a bad tag for UOP version 3.4.0+.
The change for that was made in https://github.com/loot/oblivion/commit/8d41ad075ee8c75e1214f6a0fad2e9078c75cace
Maybe @Sharlikran or @Arthmoor can shed some light on it.

**Comment by MacSplody** [comment]
An older change for the UOP `C.Water` tags.
https://github.com/loot/oblivion/commit/e3b35575deacee04b295e2f101a7f927242d542f

**Comment by Arthmoor** [comment]
I remember that having been done, but it was Kivan who originally removed it from the file and he never said why. I never gave much thought to it after those commits were made.

I think the tag should be put back into place though because the UOP and USIP both edit several bits of water data due to bugs and leaving this tag off means those will just get lost and the bugs won't actually be fixed.
