### ISSUE TITLE
DibellasWatch and Morroblivion 

### ISSUE THREAD

**Issue by llde** [loot/oblivion#368]
DibellasWatch.esm and Morrowind_ob.esm  are marked as incompatible (both rely on being a index 01), but it's incompatibility is fixed by EngineBugFixes (it fixes the bug caused when one of them isn't at index 01).

**Comment by sibir-ine** [comment]
@llde 

Just for reference, some recent discussion on the topic: https://github.com/loot/oblivion/issues/232#issuecomment-797930909 https://github.com/loot/oblivion/issues/232#issuecomment-798784105 https://github.com/loot/oblivion/issues/232#issuecomment-798830390 https://github.com/loot/oblivion/issues/232#issuecomment-798903846 https://github.com/loot/oblivion/pull/255

I'm assuming the patch that addresses this issue is the TerrainLODLoadPatch from EBF? If so, we could disable those rules/incompatibilities if EBF is installed.

**Comment by llde** [comment]
tha patch solve one bug, the most serious one is fixed by ExteriorCellTempObjectsLoadFix

**Comment by sibir-ine** [comment]
@llde Okay, I did a bit more digging to fully understand the situation since there's a lot going on. I examined both Dibella's Watch & Morroblivion, & it appears that the "Move Worldspaces" function has actually been run on Dibella's Watch but not Morroblivion. Also, TerrainLODLoadPatch only adds support for an alternate FormID-independent naming-scheme for landscape LOD files, & Morroblivion doesn't use it. Therefore, Morroblivion will have to occupy index 01, EBF or not. It also appears that Dibella's Watch is indeed affected by the bug fixed by ExteriorCellTempObjectsLoadFix, so, if EBF is installed, it can safely load elsewhere & be run with Morroblivion as you pointed out originally. I'll update the masterlist in a bit to reflect these findings.

One thing I forgot to consider is that group metadata can't be disabled conditionally, so we can't really remove Dibella's Watch from it's current group. However, we can add a conditional load after rule to ensure Morroblivion loads before it, hopefully in index 01 assuming another mod doesn't throw a spanner in the works. Groups are also the only masterlist metadata you can manually override, so you can also assign it to a later group if needed.

**Comment by sibir-ine** [comment]
Done. Thanks for the report & for bringing attention to the issue. We originally thought the main issue was the mismatched LOD files, so it's good to know there was a similar but much more severe issue confounding the situation.

**Comment by llde** [comment]
@sibir-ine Tes4ll support dynamic generation of the landscape distand land file compatible with the new EBF scheme.

**Comment by sibir-ine** [comment]
I see. Well, I think the metadata as it is should be sufficient. You can still manually change Morroblivion's group assignment, & we can review the afters if they cause a problem.
