### ISSUE TITLE
Global messages to recommend OBSE plugins

### ISSUE THREAD

**Issue by MacSplody** [loot/oblivion#90]
Considering adding a global messages to recommend installing plugins that are essential for stability and performance.

### [EngineBugFixes](https://www.nexusmods.com/oblivion/mods/47085)

> An OBSE plugin containing bug fixes for the Oblivion game engine. 

### [OBL Mod Limit Fix](https://www.nexusmods.com/oblivion/mods/50066)

> This plugin fixes the Oblivion mod limit bug. It allows a maximum of 255 plugins to be loaded. 
> The game has a hard coded limit of 512 maximum file handles that could be opened at once. This fix simply bumps that up to 2048 to allow for more room for file handles. I picked 2048 because it is the maximum number that Windows usually allows and the more the merrier.

### [SkyBSA](https://www.nexusmods.com/oblivion/mods/49568)

> An OBSE DLL that forces Oblivion to handle BSAs and loose files the same way that Skyrim does. No more mucking around with file timestamps!

**Comment by Sabre142** [comment]
What about NVAC - New Vegas Anti Crash (https://www.nexusmods.com/newvegas/mods/53635)?

**Comment by MacSplody** [comment]
> What about [NVAC - New Vegas Anti Crash](https://www.nexusmods.com/newvegas/mods/53635)?

Yeah, it could be an option. I'm still only mulling over adding these as it might be too intrusive.

**Comment by sibir-ine** [comment]
I don't think it would be too intrusive to add these globals, especially if they're just `say`s. Considering how much they can increase stability & performance, I think it's reasonable to gently nudge users to consider using them. They could be made even less intrusive by only showing them if the user has OBSE installed, though I think it's still worth letting all users know these plugins exist.

**Comment by pStyl3** [comment]
I'm not so sure about this. The question is where would we display these global messages, and under which conditions?

Let's take a look at the number for Total Downloads for each of the mentioned mods.

EngineBugFixes - 301,663
OBL Mod Limit Fix - 19,802
SkyBSA - 43,778
NVAC - New Vegas Anti Crash - 3,940,635

The big one of these 4 is NVAC, it has more than 10x the amount of downloads than the other 3 combined. Even with this situation I would be against displaying an unconditional recommendation for NVAC, and against it being displayed in LOOT's `General Information` card at the top of LOOT's right pane, regardless if it is conditional or not (of course, if NVAC had problems that would be another story).

There are a number of reasons for this:
- LOOT should always display plugin specific information. Linking mods for the sake of it and without a real need isn't really LOOT's job. Plus, even for popular mods like NVAC there are multiple people who do not want or do not trust such mods, and they rather play vanilla than with patch mods .. they would not like to see such a message. This situation is even more intricate and delicate for mods that are not (yet) widely accepted and used.
- In case we would link those mods via global messages, which conditions would be used to display them? I'm not sure that using OBSE would warrant displaying them.

If we were to find specific condiitons and specfic plugins for which such messages would fit, yeah why not, but otherwise I'm not convinced that we should persue this.

**Comment by llde** [comment]
NVAC in Oblivion is mostly useless, and actually harmful in ModOrganizer environments. The causes of the instability between the virtual file system/nvac and Oblivion  isn't well know, but it exist. Maybe it come  from  the different ways on how OBSE is injected respect to NVSE.
(And despite what some guides suggest nvac in Oblivion just install a global exception handler that do almost nothing + a fix for a windows + nvidia driver  bug that was already fixed a couple of years ago)

There are some mods that tend to trigger some engine bugs fixed by EngineBugFixes and so it state it as requirement. An example is KvatchRebuilt. Maybe it may be worth to display a single message for EBF and EBF alone, if such mods are present in the load order.

**Comment by sibir-ine** [comment]
> There are some mods that tend to trigger some engine bugs fixed by EngineBugFixes and so it state it as requirement. An example is KvatchRebuilt. Maybe it may be worth to display a single message for EBF and EBF alone, if such mods are present in the load order.

@llde Yeah, if a mod lists it as a requirement or recommendation, we have messages/keys to display those. We'll double-check Kvatch Rebuilt, thanks for pointing it out.

**Comment by sibir-ine** [comment]
Upon further reflection, unconditional global messages for these plugins may be too intrusive. We don't even have global messages recommending much less controversial mods like the Unofficial Patches, so, if we want to pursue something like this, I think we should set out some more rigorous guidelines for what mods should be recommended to users & why. We should also hold off until a feature that allows users to hide messages is implemented to make the messages as unintrusive as possible (assuming we decide to go through with this).

**Comment by MacSplody** [comment]
I'll close this for now as there isn't a watertight reason to add them.
